version: "2.4"

services:
  ns-express:
      build:
        context: .
        target: dev
        args:
          - NODE_ENV=development
        dockerfile: ./express.Dockerfile
      ports:
        - 3001:3001
      volumes:
        - ./ns/.:/node/app
        - /node/app/node_modules
      env_file:
        - ./.env/app.env

  ns-mongo:
    build:
      context: .
      dockerfile: ./mongo.Dockerfile
    command: --auth --port 27018
    ports: 
      - 27018:27018
    env_file:
      - ./.env/app.env